experiment:
  name:
    slrw_train_256
  max_broken: 10000
  max_trials: 25
  working_dir:
    orion_working_dir
  algorithms:
    random
  strategy:
    MaxParallelStrategy
evc:
  ignore_code_changes:
    true
